protected/controllers/PostController.php
<?php

class PostController extends Controller
{
    public function actionIndex()
    {
        $model = Post::model()->findAll();
        $this->render('index', array('model' => $model));
    }

    public function actionView($id, $url = '')
    {
        $model = Post::model()->findByPk($id);
        if (!$model)
            throw new CHttpException(404, 'Указанная страница не найдена');
        elseif ($url != '' && $model->url != $url)
            throw new CHttpException(404, 'Указанная страница не найдена');
        
        if ($url === '') {
            $url = $model->url;
            $this->redirect('/post/'.$id.'/'.$url, true, 301);
        }
        
        // SEO
        $this->pageTitle = $model->title;
        $this->description = $model->description;
        $this->keywords = $model->keywords;
        
        // Генерация шаблона и вывод на экран
        $this->render('view', array('model' => $model));
    }
	// Uncomment the following methods and override them if needed
	/*
	public function filters()
	{
		// return the filter configuration for this controller, e.g.:
		return array(
			'inlineFilterName',
			array(
				'class'=>'path.to.FilterClass',
				'propertyName'=>'propertyValue',
			),
		);
	}

	public function actions()
	{
		// return external action classes, e.g.:
		return array(
			'action1'=>'path.to.ActionClass',
			'action2'=>array(
				'class'=>'path.to.AnotherActionClass',
				'propertyName'=>'propertyValue',
			),
		);
	}
	*/
}

protected/controllers/SiteController.php
<?php

class SiteController extends Controller
{
	/**
	 * Declares class-based actions.
	 */
	public function actions()
	{
		return array(
			// captcha action renders the CAPTCHA image displayed on the contact page
			'captcha'=>array(
				'class'=>'CCaptchaAction',
				'backColor'=>0xFFFFFF,
			),
			// page action renders "static" pages stored under 'protected/views/site/pages'
			// They can be accessed via: index.php?r=site/page&view=FileName
			'page'=>array(
				'class'=>'CViewAction',
			),
		);
	}

	/**
	 * This is the default 'index' action that is invoked
	 * when an action is not explicitly requested by users.
	 */
	public function actionIndex()
	{
            // echo Yii::app()->request->getHostInfo();
            // SEO
            $this->pageTitle = 'Подготовка к экзамену по 1С Профессионал Платформа 8.2';
            $this->description = '1С Предприятие подготовка к экзамену по платформе 8.2';
            $this->keywords = '1с предприятие экзамен подготовка профессионал платформа';
            
            $this->render('index');
	}

	/**
	 * This is the action to handle external exceptions.
	 */
	public function actionError()
	{
		if($error=Yii::app()->errorHandler->error)
		{
			if(Yii::app()->request->isAjaxRequest)
				echo $error['message'];
			else
				$this->render('error', $error);
		}
	}

	/**
	 * Displays the contact page
	 */
	public function actionContact()
	{
		$model=new ContactForm;
		if(isset($_POST['ContactForm']))
		{
			$model->attributes=$_POST['ContactForm'];
			if($model->validate())
			{
				$name='=?UTF-8?B?'.base64_encode($model->name).'?=';
				$subject='=?UTF-8?B?'.base64_encode($model->subject).'?=';
				$headers="From: $name <{$model->email}>\r\n".
					"Reply-To: {$model->email}\r\n".
					"MIME-Version: 1.0\r\n".
					"Content-Type: text/plain; charset=UTF-8";

				mail(Yii::app()->params['adminEmail'],$subject,$model->body,$headers);
				Yii::app()->user->setFlash('contact','Thank you for contacting us. We will respond to you as soon as possible.');
				$this->refresh();
			}
		}
		$this->render('contact',array('model'=>$model));
	}

	/**
	 * Displays the login page
	 */
	public function actionLogin()
	{
		$model=new LoginForm;

		// if it is ajax validation request
		if(isset($_POST['ajax']) && $_POST['ajax']==='login-form')
		{
			echo CActiveForm::validate($model);
			Yii::app()->end();
		}

		// collect user input data
		if(isset($_POST['LoginForm']))
		{
			$model->attributes=$_POST['LoginForm'];
			// validate user input and redirect to the previous page if valid
			if($model->validate() && $model->login())
				$this->redirect(Yii::app()->user->returnUrl);
		}
		// display the login form
		$this->render('login',array('model'=>$model));
	}

	/**
	 * Logs out the current user and redirect to homepage.
	 */
	public function actionLogout()
	{
		Yii::app()->user->logout();
		$this->redirect(Yii::app()->homeUrl);
	}
        
        /*
         * Регистрация нового пользователя.
         */
	public function actionRegister()
	{
            $this->render('register');
	}
        
        /*
         * Отзывы пользователей.
         */
	public function actionReviews()
	{
            $this->render('reviews');
	}
}

protected/controllers/TestingController.php
<?php

class TestingController extends Controller
{
    public $layout='//layouts/column2';
    
    public function filters() {
        return array(
            'ajaxOnly + checkanswer', // action'ы вызываемые только ajax'ом.
        );
    }
    
    /*
     * Главная страница Тестирования.
     */
    public function actionIndex()
    {
        // SEO
        $this->pageTitle = 'Тестирование по 1С Предприятие Платформа 8.2';
        $this->description = 'Пробное тестирование по 1С Предприятие Платформа 8.2';
        $this->keywords = 'тестирование пробное 1с профессионал платформа подготовка';

        $this->render('index');
    }

    public function actionGo()
    {
        // С какого Раздела начать тест - $_POST['tnq']
        $post_tnq = (int)Yii::app()->request->getPost('tnq', 1);
        
        // SEO
        $this->pageTitle = 'Начало тестирования по 1С Профессионал Платформа 8.2';
        $this->description = 'Начало пробного тестирования по 1С Профессионал Платформа 8.2';
        $this->keywords = 'начало тестирование 1с профессионал платформа';
        
        // Обнуляем массив сессии testing
        $session=new CHttpSession;
        $session->open();
        unset($session['testing']);
        
        /*
         * jQuery скрипт, который ajax'ом отправляет вариант ответа пользователя по адресе /testing/checkanswer.
         * Также отправляется id и num_quest текущего вопроса.
         */
        Yii::app()->clientScript->registerScript(
                'checkAnswer',
                'jQuery("body").on("click", "input[name=answer]", function() {
                    var answer_id = $(this).attr("alt");
                    var quest_id = $("input[name=quest_id]").val();
                    var num_quest = $("input[name=num_quest]").val();
                    jQuery.ajax({
                        data:{"answer_id": answer_id,"num_quest": num_quest, "quest_id": quest_id},
                        url:"/testing/checkanswer",
                        cache:false,
                        success:function(html){
                            jQuery(".large-9").html(html)
                            }
                        });
                    return false;
                    });',
                CClientScript::POS_READY);
        
        $pid = 1; // platform_id - id платформы, по которой проводится тест
        $tnq = ($post_tnq > 1 && $post_tnq < 15) ? $post_tnq : 1; // top num_quest - верхняя цифра номера вопроса
        $bnq = $tnq + 1; // bottom num_quest - нижняя цифра номера вопроса
        $session['tnq'] = $tnq;
        
        $model = Question::model()->with('answers')->with('image')->findAll(
                'platform_id = :pid AND num_quest >= :tnq AND num_quest < :bnq',
                array(':pid' => $pid, ':tnq' => $tnq, ':bnq' => $bnq));
        
        if (!$model) {
            throw new CHttpException(400,'Некорректный запрос.');
        }
        
        $quests = count($model); // количество вопросов в разделе
        $curQuest = rand(0, $quests-1); // текущий случайный вопрос
        
        $this->render('go', array('model' => $model[$curQuest]));
    }
    
    public function actionCheckAnswer()
    {
        $quest_id = (int)Yii::app()->request->getQuery('quest_id', 0); // текущий id вопроса
        $num_quest = Yii::app()->request->getQuery('num_quest', 0);
        $answer_id = (int)Yii::app()->request->getQuery('answer_id', 0); // id ответа пользователя
        $true_answ = Answer::model()->findByPk($answer_id)->true_answ; // ответ был правильным (1) или нет (0)
        
        // Открываем сессию
        $session=new CHttpSession;
        $session->open();
        
        // К массиву testing добавляем очередной массив значений вопроса и ответа пользователя
        $testing = array();
        if (isset($session['testing']))
            $testing = $session['testing'];
        $testing[] = array('quest_id' => $quest_id, 'num_quest' => $num_quest, 'answer_id' => $answer_id, 'true_answ' => $true_answ);
        $session['testing'] = $testing;
        
        // print_r($session['testing']);
        
        $pid = 1; // platform_id - id платформы, по которой проводится тест        
        $tnq = (int)$num_quest + 1; // top num_quest - верхняя цифра номера вопроса
        $bnq = $tnq + 1; // bottom num_quest - нижняя цифра номера вопроса
        
        $model = Question::model()->with('answers')->with('image')->findAll(
                'platform_id = :pid AND num_quest >= :tnq AND num_quest < :bnq',
                array(':pid' => $pid, ':tnq' => $tnq, ':bnq' => $bnq));
        
        // Если вопросов больше нет, то ТЕСТ считается завершенным
        if (!$model) {
            $result = array();
            $f_answ = array();
            $result['count_all'] = count($testing);
            $result['count_true'] = 0;
            foreach ($testing as $t) {
                ($t['true_answ']) ? $result['count_true']++ : null;
                (!$t['true_answ']) ? $f_answ[$t['quest_id']] = $t['num_quest'] : null;
            }
            $result['false_answ'] = $f_answ;
            $result['success'] = (($result['count_true']/$result['count_all']) > 0.85) ? 1 : 0;
            
            $this->renderPartial('result', array('result' => $result, 'tnq' => $session['tnq']));
            Yii::app()->end();
        }
        
        $quests = count($model); // количество вопросов в разделе
        $curQuest = rand(0, $quests-1); // текущий случайный вопрос
        
        $this->renderPartial('go', array('model' => $model[$curQuest]));
    }

    // Uncomment the following methods and override them if needed
    /*
    public function filters()
    {
            // return the filter configuration for this controller, e.g.:
            return array(
                    'inlineFilterName',
                    array(
                            'class'=>'path.to.FilterClass',
                            'propertyName'=>'propertyValue',
                    ),
            );
    }

    public function actions()
    {
            // return external action classes, e.g.:
            return array(
                    'action1'=>'path.to.ActionClass',
                    'action2'=>array(
                            'class'=>'path.to.AnotherActionClass',
                            'propertyName'=>'propertyValue',
                    ),
            );
    }
    */
}

protected/views/layouts/column1.php
<?php /* @var $this Controller */ ?>
<?php $this->beginContent('//layouts/main'); ?>
<div class="row">
    <div class="large-12 columns">
<?php echo $content; ?>
    </div>
</div>
<?php $this->endContent(); ?>

protected/views/layouts/column2.php
<?php /* @var $this Controller */ ?>
<?php $this->beginContent('//layouts/main'); ?>
<div class="row">
    <div class="large-9 columns">
<?php echo $content; ?>
    </div>
    <div class="large-3 columns">
    </div>
</div>
<?php $this->endContent(); ?>

protected/views/layouts/main.php
<?php /* @var $this Controller */ ?>
<!DOCTYPE html>
<html>
<head>
    <meta http-equiv="Content-Type" content="text/html; charset=utf-8" />
    <meta name="Description" content="<?php echo CHtml::encode($this->description); ?>"/>
    <meta name="Keywords" content="<?php echo CHtml::encode($this->keywords); ?>"/>
    <title><?php echo CHtml::encode($this->pageTitle); ?></title>

    <!-- foundation CSS framework -->
    <link rel="stylesheet" type="text/css" href="<?php echo Yii::app()->request->baseUrl; ?>/css/foundation.min.css" />
    <link rel="stylesheet" type="text/css" href="<?php echo Yii::app()->request->baseUrl; ?>/css/style.css" />    

    <!-- foundation framework JS -->
    <!-- <script src="<?php echo Yii::app()->request->baseUrl; ?>/js/modernizr.js"></script> -->
    <!-- <script src="<?php echo Yii::app()->request->baseUrl; ?>/js/foundation.min.js"></script> -->
</head>

<body>

<!--noindex-->
<div class="row">
    <div class="large-12 columns">
	<div class="loginmenu right">
		<?php $this->widget('zii.widgets.CMenu',array(
			'items'=>array(
				array('label'=>'Войти', 'url'=>array('/site/login'), 'visible'=>Yii::app()->user->isGuest, 'linkOptions'=>array('rel'=>'nofollow')),
				array('label'=>'Регистрация', 'url'=>array('/site/register'), 'visible'=>Yii::app()->user->isGuest, 'linkOptions'=>array('rel'=>'nofollow')),
				array('label'=>'Выйти ('.Yii::app()->user->name.')', 'url'=>array('/site/logout'), 'visible'=>!Yii::app()->user->isGuest, 'linkOptions'=>array('rel'=>'nofollow'))
			),
		)); ?>
	</div>
    </div>
</div>
<!--/noindex-->
<div class="row">
    <div class="large-12 columns">
        <nav class="top-bar" data-topbar>
            <ul class="title-area">
                <li class="name">
                    <?php if(Yii::app()->request->pathInfo == ''): ?>
                        <div><img src="/images/logo_test1c.png" alt="1С Тренинг - твой путь к победе" title="1С Тренинг. Тренировка - твой путь к победе" /></div>
                    <?php else: ?>
                        <a href="/" rel="nofollow"><img src="/images/logo_test1c.png" alt="1С Тренинг - твой путь к победе" title="1С Тренинг. Тренировка - твой путь к победе" /></a>
                    <?php endif; ?>
                </li>
            </ul>
            <section class="top-bar-section">
                <ul class="right">
                    <li class="divider"></li>
                    <li <?= strstr(Yii::app()->request->pathInfo, 'post') ? 'class="active"' : ''; ?>><?= CHtml::link('Статьи', array('/post/index'), array('rel' => strstr(Yii::app()->request->pathInfo, 'post') ? 'nofollow' : '')); ?></li>
                    <li class="divider"></li>
                    <li <?= strstr(Yii::app()->request->pathInfo, 'training') ? 'class="active"' : ''; ?>><?= CHtml::link('Тренинг', array('/training/index'), array('rel' => strstr(Yii::app()->request->pathInfo, 'training') ? 'nofollow' : '')); ?></li>
                    <li class="divider"></li>
                    <li <?= strstr(Yii::app()->request->pathInfo, 'testing') ? 'class="active"' : ''; ?>><?= CHtml::link('Тестирование', array('/testing/index'), array('rel' => strstr(Yii::app()->request->pathInfo, 'testing') ? 'nofollow' : '')); ?></li>
                    <li class="divider"></li>
                    <li <?= strstr(Yii::app()->request->pathInfo, 'reviews') ? 'class="active"' : ''; ?>><?= CHtml::link('Отзывы', array('/site/reviews'), array('rel' => strstr(Yii::app()->request->pathInfo, 'reviews') ? 'nofollow' : '')); ?></li>
                </ul>
            </section>
        </nav>
    </div>
</div>

<!--noindex-->
<div class="row">
    <div class="large-12 columns">
	<?php if(isset($this->breadcrumbs)):?>
		<?php $this->widget('zii.widgets.CBreadcrumbs', array(
			'links' => $this->breadcrumbs,
                        'homeLink' => '<li>' . CHtml::link('Главная', array('site/index'), array('rel' => 'nofollow')) . '</li>',
                        'tagName' => 'ul',
                        'separator' => '',
                        'activeLinkTemplate' => '<li><a href="{url}" rel="nofollow">{label}</a></li>',
                        'inactiveLinkTemplate' => '<li class="current">{label}</li>',
		)); ?><!-- breadcrumbs -->
	<?php endif?>
        <hr/>
    </div>
</div>
<!--/noindex-->

<div id="content">
<?php echo $content; ?>
</div>

<div class="row">
    <div class="large-12 columns">
        <div class="footer text-right">Development by Yii Framework. Все права защищены. 2011-<?= date('Y'); ?>. <!--noindex--><a href="mailto:admin@test1c.org?subject=Feedback%20from%20-%20test1c.org" rel="nofollow">@admin</a><!--/noindex--></div>
    </div>
</div>

<!--noindex-->
<br/>
<div class="row">
    <div class="large-12 columns text-right">
    
<!-- Rating@Mail.ru counter -->
<script type="text/javascript">//<![CDATA[
var _tmr = _tmr || [];
_tmr.push({id: "2458451", type: "pageView", start: (new Date()).getTime()});
(function (d, w) {
   var ts = d.createElement("script"); ts.type = "text/javascript"; ts.async = true;
   ts.src = (d.location.protocol == "https:" ? "https:" : "http:") + "//top-fwz1.mail.ru/js/code.js";
   var f = function () {var s = d.getElementsByTagName("script")[0]; s.parentNode.insertBefore(ts, s);};
   if (w.opera == "[object Opera]") { d.addEventListener("DOMContentLoaded", f, false); } else { f(); }
})(document, window);
//]]></script><noscript><div style="position:absolute;left:-10000px;">
<img src="//top-fwz1.mail.ru/counter?id=2458451;js=na" style="border:0;" height="1" width="1" alt="Рейтинг@Mail.ru" />
</div></noscript>
<!-- //Rating@Mail.ru counter -->

<!-- Rating@Mail.ru logo -->
<a href="http://top.mail.ru/jump?from=2458451">
<img src="//top-fwz1.mail.ru/counter?id=2458451;t=281;l=1" 
style="border:0;" height="31" width="38" alt="Рейтинг@Mail.ru" /></a>
<!-- //Rating@Mail.ru logo -->

<!-- Yandex.Metrika counter --><script type="text/javascript">(function (d, w, c) { (w[c] = w[c] || []).push(function() { try { w.yaCounter18753502 = new Ya.Metrika({id:18753502, clickmap:true, accurateTrackBounce:true}); } catch(e) { } }); var n = d.getElementsByTagName("script")[0], s = d.createElement("script"), f = function () { n.parentNode.insertBefore(s, n); }; s.type = "text/javascript"; s.async = true; s.src = (d.location.protocol == "https:" ? "https:" : "http:") + "//mc.yandex.ru/metrika/watch.js"; if (w.opera == "[object Opera]") { d.addEventListener("DOMContentLoaded", f, false); } else { f(); } })(document, window, "yandex_metrika_callbacks");</script><noscript><div><img src="//mc.yandex.ru/watch/18753502" style="position:absolute; left:-9999px;" alt="" /></div></noscript><!-- /Yandex.Metrika counter -->

<!--LiveInternet counter--><script type="text/javascript">document.write("<a href='http://www.liveinternet.ru/click' target=_blank><img src='//counter.yadro.ru/hit?t44.5;r" + escape(document.referrer) + ((typeof(screen)=="undefined")?"":";s"+screen.width+"*"+screen.height+"*"+(screen.colorDepth?screen.colorDepth:screen.pixelDepth)) + ";u" + escape(document.URL) + ";" + Math.random() + "' border=0 width=31 height=31 alt='' title='LiveInternet'><\/a>")</script><!--/LiveInternet-->

    </div>
</div>
<!--/noindex-->

</body>

</html>

protected/views/layouts/main_2.php
<?php /* @var $this Controller */ ?>
<!DOCTYPE html>
<html>
<head>
    <meta http-equiv="Content-Type" content="text/html; charset=utf-8" />
    <meta name="Description" content="<?php echo CHtml::encode($this->description); ?>"/>
    <meta name="Keywords" content="<?php echo CHtml::encode($this->keywords); ?>"/>
    <title><?php echo CHtml::encode($this->pageTitle); ?></title>

    <!-- foundation CSS framework -->
    <link rel="stylesheet" type="text/css" href="<?php echo Yii::app()->request->baseUrl; ?>/css/foundation.min.css" />
    <link rel="stylesheet" type="text/css" href="<?php echo Yii::app()->request->baseUrl; ?>/css/style.css" />    

    <!-- foundation framework JS -->
    <!-- <script src="<?php echo Yii::app()->request->baseUrl; ?>/js/modernizr.js"></script> -->
    <!-- <script src="<?php echo Yii::app()->request->baseUrl; ?>/js/foundation.min.js"></script> -->
</head>

<body>

<!--noindex-->
<div class="row">
    <div class="large-12 columns">
	<div class="loginmenu right">
		<?php $this->widget('zii.widgets.CMenu',array(
			'items'=>array(
				array('label'=>'Войти', 'url'=>array('/site/login'), 'visible'=>Yii::app()->user->isGuest, 'linkOptions'=>array('rel'=>'nofollow')),
				array('label'=>'Регистрация', 'url'=>array('/site/register'), 'visible'=>Yii::app()->user->isGuest, 'linkOptions'=>array('rel'=>'nofollow')),
				array('label'=>'Выйти ('.Yii::app()->user->name.')', 'url'=>array('/site/logout'), 'visible'=>!Yii::app()->user->isGuest, 'linkOptions'=>array('rel'=>'nofollow'))
			),
		)); ?>
	</div>
    </div>
</div>
<!--/noindex-->
<div class="row">
    <div class="large-12 columns">
        <nav class="top-bar" data-topbar>
            <ul class="title-area">
                <li class="name">
                    <?php if(Yii::app()->request->pathInfo == ''): ?>
                        <div>1С Тренинг</div>
                    <?php else: ?>
                        <a href="/" rel="nofollow">1С Тренинг</a>
                    <?php endif; ?>
                </li>
            </ul>
            <section class="top-bar-section">
                <ul class="right">
                    <li class="divider"></li>
                    <li <?= strstr(Yii::app()->request->pathInfo, 'training') ? 'class="active"' : ''; ?>><?= CHtml::link('Тренинг', array('/training/index'), array('rel' => strstr(Yii::app()->request->pathInfo, 'training') ? 'nofollow' : '')); ?></li>
                    <li class="divider"></li>
                    <li <?= strstr(Yii::app()->request->pathInfo, 'testing') ? 'class="active"' : ''; ?>><?= CHtml::link('Тестирование', array('/testing/index'), array('rel' => strstr(Yii::app()->request->pathInfo, 'testing') ? 'nofollow' : '')); ?></li>
                    <li class="divider"></li>
                    <li <?= strstr(Yii::app()->request->pathInfo, 'reviews') ? 'class="active"' : ''; ?>><?= CHtml::link('Отзывы', array('/site/reviews'), array('rel' => strstr(Yii::app()->request->pathInfo, 'reviews') ? 'nofollow' : '')); ?></li>
                </ul>
            </section>
        </nav>
    </div>
</div>

<!--noindex-->
<div class="row">
    <div class="large-12 columns">
	<?php if(isset($this->breadcrumbs)):?>
		<?php $this->widget('zii.widgets.CBreadcrumbs', array(
			'links' => $this->breadcrumbs,
                        'homeLink' => '<li>' . CHtml::link('Главная', array('site/index'), array('rel' => 'nofollow')) . '</li>',
                        'tagName' => 'ul',
                        'separator' => '',
                        'activeLinkTemplate' => '<li><a href="{url}" rel="nofollow">{label}</a></li>',
                        'inactiveLinkTemplate' => '<li class="current">{label}</li>',
		)); ?><!-- breadcrumbs -->
	<?php endif?>
        <hr/>
    </div>
</div>
<!--/noindex-->

<div id="content">
<?php echo $content; ?>
</div>

<div class="row">
    <div class="large-12 columns">
        <div class="footer text-right">Development by Yii Framework. Все права защищены. 2011-<?= date('Y'); ?>. <!--noindex--><a href="mailto:admin@test1c.org?subject=Feedback%20from%20-%20test1c.org" rel="nofollow">@admin</a><!--/noindex--></div>
    </div>
</div>

<!--noindex-->
<br/>
<div class="row">
    <div class="large-12 columns text-right">
    
<!-- Rating@Mail.ru counter -->
<script type="text/javascript">//<![CDATA[
var _tmr = _tmr || [];
_tmr.push({id: "2458451", type: "pageView", start: (new Date()).getTime()});
(function (d, w) {
   var ts = d.createElement("script"); ts.type = "text/javascript"; ts.async = true;
   ts.src = (d.location.protocol == "https:" ? "https:" : "http:") + "//top-fwz1.mail.ru/js/code.js";
   var f = function () {var s = d.getElementsByTagName("script")[0]; s.parentNode.insertBefore(ts, s);};
   if (w.opera == "[object Opera]") { d.addEventListener("DOMContentLoaded", f, false); } else { f(); }
})(document, window);
//]]></script><noscript><div style="position:absolute;left:-10000px;">
<img src="//top-fwz1.mail.ru/counter?id=2458451;js=na" style="border:0;" height="1" width="1" alt="Рейтинг@Mail.ru" />
</div></noscript>
<!-- //Rating@Mail.ru counter -->

<!-- Rating@Mail.ru logo -->
<a href="http://top.mail.ru/jump?from=2458451">
<img src="//top-fwz1.mail.ru/counter?id=2458451;t=281;l=1" 
style="border:0;" height="31" width="38" alt="Рейтинг@Mail.ru" /></a>
<!-- //Rating@Mail.ru logo -->

<!-- Yandex.Metrika counter --><script type="text/javascript">(function (d, w, c) { (w[c] = w[c] || []).push(function() { try { w.yaCounter18753502 = new Ya.Metrika({id:18753502, clickmap:true, accurateTrackBounce:true}); } catch(e) { } }); var n = d.getElementsByTagName("script")[0], s = d.createElement("script"), f = function () { n.parentNode.insertBefore(s, n); }; s.type = "text/javascript"; s.async = true; s.src = (d.location.protocol == "https:" ? "https:" : "http:") + "//mc.yandex.ru/metrika/watch.js"; if (w.opera == "[object Opera]") { d.addEventListener("DOMContentLoaded", f, false); } else { f(); } })(document, window, "yandex_metrika_callbacks");</script><noscript><div><img src="//mc.yandex.ru/watch/18753502" style="position:absolute; left:-9999px;" alt="" /></div></noscript><!-- /Yandex.Metrika counter -->

<!--LiveInternet counter--><script type="text/javascript">document.write("<a href='http://www.liveinternet.ru/click' target=_blank><img src='//counter.yadro.ru/hit?t44.5;r" + escape(document.referrer) + ((typeof(screen)=="undefined")?"":";s"+screen.width+"*"+screen.height+"*"+(screen.colorDepth?screen.colorDepth:screen.pixelDepth)) + ";u" + escape(document.URL) + ";" + Math.random() + "' border=0 width=31 height=31 alt='' title='LiveInternet'><\/a>")</script><!--/LiveInternet-->

    </div>
</div>
<!--/noindex-->

</body>

</html>